commands:
  adventure: True
  beg: True
  crime: True
  daily: True
  dig: True
  fish: True
  guess: False
  highlow: True
  hunt: True
  postmeme: True
  search: True
  trivia: True
  vote: True
  work: True

lottery:
  enabled: False
  cooldown: 3600

stream:
  enabled: True
  ads: True
  chat: True
  donations: True

blackjack:
  enabled: False
  random: False
  amount: 1500
  minimum: 1500
  maximum: 3000

snakeeyes:
  enabled: False
  random: False
  amount: 1500
  minimum: 1500
  maximum: 3000

cooldowns:
  patron: False
  timeout: 5

custom commands:
  enabled: False
  pls dep max:
    enabled: True
    cooldown: 300

shifts:
  enabled: False
  active: 7200
  passive: 3600
  
auto buy:
  enabled: True
  shovel: True
  fishing pole: True
  hunting rifle: True
  keyboard: True
  mouse: True
  adventure ticket: True

auto trade:
  enabled: False
  trader token: None
  bank note: True
  tidepod: True

auto accept trade:
  enabled: True
  traders: [0, 0]

auto sell:
  enabled: False
  apple: True
  common fish: True

typing indicator:
  enabled: False
  minimum: 0
  maximum: 0.5

message delay:
  enabled: False
  minimum: 0
  maximum: 0.5

button delay:
  enabled: False
  minimum: 0
  maximum: 0.5

dropdown delay:
  enabled: False
  minimum: 0
  maximum: 0.5

anti heist:
  enabled: True

auto join heist:
  enabled: True

auto start:
  enabled: False
  channels: ["channel_id_1", "channel_id_2"]

blacklisted servers:
  enabled: False
  servers: ["guild_id_1", "guild_id_2"]

logging:
  debug: True
  warning: True